// Catálogo de hábitos predefinidos (MVP)
// Cada entrada: { id, name, category }

const PER_CATEGORY = {
  'Salud Física': [
    'Caminar 30 minutos',
    'Beber 8 vasos de agua',
    'Dormir 7-8 horas',
    'Estirar 10 minutos',
    'Comer 2 piezas de fruta',
    'Hacer 20 sentadillas',
    'Evitar ultraprocesados hoy',
    'Tomar el sol 10 minutos',
    'Postura consciente 5 minutos',
    'Subir escaleras 5 veces',
  ],
  'Salud Mental': [
    'Meditar 10 minutos',
    'Escribir 3 gratitudes',
    'Respirar conscientemente 5 minutos',
    'Desconexión digital 30 minutos',
    'Paseo consciente 15 minutos',
    'Lectura relajante 20 minutos',
    'Diario emocional 10 minutos',
    'Afirmaciones positivas 5 minutos',
    'Siesta breve (power nap)',
    'Evitar multitarea 1 hora',
  ],
  'Finanzas': [
    'Registrar gastos diarios',
    'Revisar presupuesto semanal',
    'Ahorrar una cantidad fija',
    'No gastos hormiga hoy',
    'Comparar precios antes de comprar',
    'Revisar suscripciones',
    'Planificar compra semanal',
    'Transferir ahorro automático',
    'Anotar 1 mejora financiera',
    'Revisar objetivo de ahorro',
  ],
  'Carrera/Estudios': [
    'Leer 20 minutos',
    'Practicar una habilidad 30 minutos',
    'Planificar el día laboral',
    'Bloque de enfoque 25 min (Pomodoro)',
    'Actualizar lista de tareas',
    'Aprender 1 concepto nuevo',
    'Revisar objetivos semanales',
    'Networking: escribir a un colega',
    'Refactorizar/repasar apuntes',
    'Organizar escritorio 10 min',
  ],
  'Relaciones Familiares': [
    'Llamar a un familiar',
    'Compartir una comida en familia',
    'Escucha activa 10 minutos',
    'Plan familiar para el fin de semana',
    'Juego/actividad con hijos 20 min',
    'Mensaje de aprecio a un familiar',
    'Revisar calendario familiar',
    'Paseo con la familia',
    'Cocinar juntos',
    'Revisar presupuesto familiar',
  ],
  'Relaciones Sociales': [
    'Contactar a un amigo',
    'Participar en actividad social',
    'Responder mensajes pendientes',
    'Invitar a café a un colega',
    'Apoyar a alguien con un detalle',
    'Comentar en comunidad online',
    'Asistir a evento local',
    'Presentarte a alguien nuevo',
    'Planear reunión grupal',
    'Agradecer a alguien su ayuda',
  ],
  'Relaciones de Pareja': [
    'Planear una cita sencilla',
    'Expresar aprecio a tu pareja',
    'Conversación sin pantallas 15 minutos',
    'Detalle cariñoso sorpresa',
    'Cocinar juntos la cena',
    'Planear actividad para dos',
    'Revisar objetivos en pareja',
    'Paseo juntos 20 minutos',
    'Mensaje romántico',
    'Resolver un pendiente juntos',
  ],
  'Desarrollo Personal': [
    'Escribir diario 10 minutos',
    'Visualizar objetivos 5 minutos',
    'Leer no ficción 20 minutos',
    'Curso online 20 minutos',
    'Revisión semanal de objetivos',
    'Aprender 5 palabras nuevas',
    'Practicar oratoria 10 minutos',
    'Crear/repasar checklist diaria',
    'Planificar mañana 10 minutos',
    'Reflexión sobre un hábito',
  ],
  'Espiritualidad': [
    'Reflexión/Oración 10 minutos',
    'Lectura espiritual 10 minutos',
    'Gratitud espiritual 3 puntos',
    'Servicio desinteresado breve',
    'Contemplación silenciosa 10 min',
    'Visitar lugar de paz',
    'Diario espiritual 10 minutos',
    'Caminar en naturaleza 15 min',
    'Respiración consciente 5 min',
    'Cita inspiradora del día',
  ],
  'Contribución a la Sociedad': [
    'Hacer un acto de amabilidad',
    'Planificar voluntariado 1h/semana',
    'Donar objetos en desuso',
    'Apoyar comercio local',
    'Participar en limpieza local',
    'Mentoría/apoyo a alguien',
    'Compartir conocimiento útil',
    'Ceder asiento/turno hoy',
    'Ahorro energético en casa',
    'Reducir plástico hoy',
  ],
  'Ocio/Diversión': [
    'Hobby 20 minutos',
    'Tiempo al aire libre',
    'Música 15 minutos',
    'Juego/rompecabezas 15 min',
    'Ver comedia 15 minutos',
    'Manualidades 20 minutos',
    'Fotografía paseo 20 min',
    'Cocinar receta nueva',
    'Leer ficción 20 minutos',
    'Planificar una excursión',
  ],
};

function toId(category, name) {
  const c = category.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  const n = name.toLowerCase().replace(/[^a-z0-9]+/g, '_');
  return `${c}_${n}`.slice(0, 60);
}

export const HABIT_CATALOG = Object.entries(PER_CATEGORY).flatMap(([category, names]) =>
  names.map((name) => ({ id: toId(category, name), name, category }))
);


